package http.GetGPSReturnData

class Body(
    val page: Int,
    val pageSize: Int,
    val token: Byte,
    val createTime: Byte,
    val updateTime: Byte,
    val gpsTime: String,
    val hbTime: String,
    val gsmSignalStrength: Int,
    val imei: String,
    val gateTime: String,
    val speed: Int,
    val direction: Int,
    val satellitesNum: Int,
    val complementFlag: String,
    val longitude: Double,
    val latitude: Double,
    val acc: String,
    val locType: String,
    val locMode: String,
    val percentageElectricQuantity: Double,
    val status: String,
    val statusUpdateTime: String,
    val deviceType: String,
    val deviceIcon: String,
    val oilState: Int,
    val chargeState: Int,
    val defencesState: Int,
    val dutyOn: Byte,
    val dutyOff: Byte,
    val extVol: Double,
    val todayTheMileage: String,
    val totalMileage: String,
    val deviceName: String
)